# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dg/dev/chess_engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dg/dev/chess_engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dg/dev/chess_engine/CMakeFiles /home/dg/dev/chess_engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dg/dev/chess_engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dev

# Build rule for target.
dev: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dev
.PHONY : dev

# fast build rule for target.
dev/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/build
.PHONY : dev/fast

src/board.o: src/board.cc.o
.PHONY : src/board.o

# target to build an object file
src/board.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/board.cc.o
.PHONY : src/board.cc.o

src/board.i: src/board.cc.i
.PHONY : src/board.i

# target to preprocess a source file
src/board.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/board.cc.i
.PHONY : src/board.cc.i

src/board.s: src/board.cc.s
.PHONY : src/board.s

# target to generate assembly for a file
src/board.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/board.cc.s
.PHONY : src/board.cc.s

src/board_display.o: src/board_display.cc.o
.PHONY : src/board_display.o

# target to build an object file
src/board_display.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/board_display.cc.o
.PHONY : src/board_display.cc.o

src/board_display.i: src/board_display.cc.i
.PHONY : src/board_display.i

# target to preprocess a source file
src/board_display.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/board_display.cc.i
.PHONY : src/board_display.cc.i

src/board_display.s: src/board_display.cc.s
.PHONY : src/board_display.s

# target to generate assembly for a file
src/board_display.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/board_display.cc.s
.PHONY : src/board_display.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/piece.o: src/piece.cc.o
.PHONY : src/piece.o

# target to build an object file
src/piece.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/piece.cc.o
.PHONY : src/piece.cc.o

src/piece.i: src/piece.cc.i
.PHONY : src/piece.i

# target to preprocess a source file
src/piece.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/piece.cc.i
.PHONY : src/piece.cc.i

src/piece.s: src/piece.cc.s
.PHONY : src/piece.s

# target to generate assembly for a file
src/piece.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/piece.cc.s
.PHONY : src/piece.cc.s

src/piece_display_manager.o: src/piece_display_manager.cc.o
.PHONY : src/piece_display_manager.o

# target to build an object file
src/piece_display_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/piece_display_manager.cc.o
.PHONY : src/piece_display_manager.cc.o

src/piece_display_manager.i: src/piece_display_manager.cc.i
.PHONY : src/piece_display_manager.i

# target to preprocess a source file
src/piece_display_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/piece_display_manager.cc.i
.PHONY : src/piece_display_manager.cc.i

src/piece_display_manager.s: src/piece_display_manager.cc.s
.PHONY : src/piece_display_manager.s

# target to generate assembly for a file
src/piece_display_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dev.dir/build.make CMakeFiles/dev.dir/src/piece_display_manager.cc.s
.PHONY : src/piece_display_manager.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dev"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/board_display.o"
	@echo "... src/board_display.i"
	@echo "... src/board_display.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/piece.o"
	@echo "... src/piece.i"
	@echo "... src/piece.s"
	@echo "... src/piece_display_manager.o"
	@echo "... src/piece_display_manager.i"
	@echo "... src/piece_display_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

